training:
  batch_size: 128
  n_epochs: 500000
  n_iters: 200001
  ngpu: 1
  snapshot_freq: 5000
  algo: 'dsm'
  num_workers: 4
  num_iter_d: 500
data:
  dataset: "MNIST"
  image_size: 28
  channels: 1
  logit_transform: false
  random_flip: false
  noise_std: 0.4 
  target_label: 8
  obj_size: 50 # Nmmber of objective samples

model:
  sigma_begin: 1
  sigma_end: 0.01
  num_classes: 10
  batch_norm: false
  ngf: 64
  ngf_d: 128

optim:
  weight_decay: 0.000
  lr: 0.000001
  lr_s: 0.001
  beta1: 0.9
  beta2: 0.999
  amsgrad: false
